# Generated by Django 6.0.2 on 2026-03-02 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quiz_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptanswer',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizzes.choice'),
        ),
    ]
