# Generated by Django 6.0.2 on 2026-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_attempt_started_at_alter_attempt_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
